format = """
[](#efd12a)\
$os\
$username\
[](bg:#efd12a fg:#1c1c1c)\
$directory\
[](fg:#1c1c1c bg:#dfc533)\
$git_branch\
$git_status\
[](fg:#dfc533 bg:#2c2c2c)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#2c2c2c bg:#d3bc3b)\
$docker_context\
[](fg:#d3bc3b bg:#3c3c3c)\
[  ](bg:#3c3c3c fg:#4ce0ee)\
$time\
[ ](fg:#3c3c3c)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#efd12a fg:#1c1c1c"
style_root = "(bg:#efd12a)"
format = '[ $user]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[directory]
style = "bg:#1c1c1c"
format = "[ $path ]($style)"
truncation_length = 6
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#d3bc3b"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#dfc533 fg:#1c1c1c"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#dfc533 fg:#1c1c1c"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
format = '[ $symbol ($version) ](bg:#2c2c2c fg:#cc6666)'

[nim]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
format = '[ $symbol ($version) ](bg:#2c2c2c fg:#D2691E)'

[scala]
symbol = " "
style = "bg:#2c2c2c"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = true
time_format = "%R:%S" # Hour:Minute Format
style = "bg:#3c3c3c"
format = '[ $time ]($style)'
